name: Deployment action
on:
  push:
    branches:
      - main

jobs:
  Test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing actions"
      - run: echo "Job status ${{ job.status }}"